name: wokflow fileters and activities
on: 
  workflow_dispatch: 
#   schedule: 
#   - cron: "*/59 * * * *" # at every 59 minutes
  push:
    # use either branches-ignore or branches
    # branches-ignore: 
    # - feature/*     # feature/add-music, feature/add-images
    # - test/**        # test/ui/index, test/checkout/paymant/
    branches: 
    - main
    - '!feature/*'  # ignoring pushes to any branch name starting with feature using !
  pull_request: 
    # all mentioned filters should satisfy
    types: 
    - opened
    - closed
    paths-ignore:   # workflow will only run when a pull request that includes a change on any file other than README.md
    - README.md
    branches: 
    - main          # configures your workflow to only run on pull requests that target specific branches
jobs:
  hello:
    runs-on: ubuntu-latest
    steps: 
    # get event name using context variable
    - run: echo this workflow/job/step is executed for event type - ${{ github.event_name}}